# Generated by Django 6.0.4 on 2026-04-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('sinopse', models.CharField(max_length=2500)),
                ('data_publicacao', models.DateField()),
                ('duracao', models.DurationField()),
                ('ultimo_segundo', models.DurationField()),
                ('thumbnail', models.BinaryField()),
            ],
        ),
    ]
