# Generated by Django 6.0.4 on 2026-07-07 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentario',
            name='ultimo_segundo',
        ),
        migrations.AlterField(
            model_name='documentario',
            name='sinopse',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='RegistroSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_segundo', models.DurationField()),
                ('documentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.documentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'documentario')},
            },
        ),
    ]
