# Generated by Django 6.0.4 on 2026-07-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_documentario_ultimo_segundo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentario',
            options={'verbose_name': 'Documentário'},
        ),
        migrations.AlterModelOptions(
            name='registrosessao',
            options={'verbose_name': 'Registro da Sessão', 'verbose_name_plural': 'Registros das Sessões'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário'},
        ),
        migrations.AddField(
            model_name='documentario',
            name='arquivo_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='documentario',
            name='endereco_video',
            field=models.URLField(blank=True),
        ),
    ]
